### ISSUE TITLE
Is it possible to include CSOS.efi in this repo?

### ISSUE THREAD

**Issue by SwordFaith** [eclypsium/BIOSDisconnect#1]
It will be much convenient to learn about how to trigger the problem.

**Comment by HackingThings** [comment]
If you want to learn more about this issue, you can watch our defcon talk at https://www.youtube.com/watch?v=qxWfkSonK7M

A link to the vulnerable CSOS efi is also included in this repo, located at https://github.com/eclypsium/BIOSDisconnect/blob/eee3456693a4bc71b788f869c08421500a014ed3/server-files/Dell/FOLDER07074784M/1/DellCsosLauncher.efi

Hopefully this answers your questions

**Comment by wrffrz** [comment]
To follow up on what HackingThings said, we intentionally didn't include the two vulnerable executables in the repo and there are a couple placeholder files with corresponding readmes that have links to the executables which have been saved on the Internet Archive's Wayback Machine.

These two placeholders contain a link to the real file and should be replaced with the version downloaded from web.archive.org:
https://github.com/eclypsium/BIOSDisconnect/blob/eee3456693a4bc71b788f869c08421500a014ed3/server-files/Dell/FOLDER07074784M/1/DellCsosLauncher.efi
https://github.com/eclypsium/BIOSDisconnect/blob/eee3456693a4bc71b788f869c08421500a014ed3/server-files/Dell/FOLDER07074779M/1/DellFOTALauncher.efi

Downloading and running compiled executables from random github repos is generally a bad idea and getting versions which have been archived by the Internet Archive is arguably a better idea.  We also didn't want to host Dell's proprietary executables in the repo here for legal reasons.

**Comment by SwordFaith** [comment]
Thanks for your helpful advice. It will be a better way to get those files by your way.
